### ISSUE TITLE
Use using blocks

### ISSUE THREAD

**Issue by vbjay** [ajstadlin/ClosedXML_Email_Testing#1]
Use using blocks instead of calling dispose.

**Comment by ajstadlin** [comment]
Thanks for the feedback!  Since it is a test app - its a good place to cut my teeth learning new techniques as well.

**Comment by ajstadlin** [comment]
```using``` does not seem to work for conditional assignments.

The following will not compile and results in an error:  

> Cannot assign to 'myXlSheet' because it is a 'using variable'

```
    using (XLWorkbook myXlBook = new XLWorkbook())
    {
        using (IXLWorksheet myXlSheet = null)
        {
            // Check to see if a specific worksheet exists, if not, Add it.
            string mySheetname = "VENUS";
            if (myXlBook.Worksheets.Where(w => w.Name == mySheetname).Count() == 0)
            {
              myXlSheet = myXlBook.Worksheets.Add(mySheetname);
              Console.WriteLine(" + worksheet created = " + mySheetname);
            }
            // worksheet building code
            // ...
        } // end using myXlSheet
    } // end using myXlBook
```

**Comment by vbjay** [comment]
That's because you are doing it wrong

XlWorkbook wb =null;
Try
{
Using (wb= new XlWorkbook())
{
....

**Comment by ajstadlin** [comment]
The XLWorkbook is not a problem to rework the code as you describe since, in this case, it is always created.

The IXLWorksheet is conditionally assigned depending on the existence of the worksheet in the workbook.  This makes it difficult to expand the code beyond the scope of the assignment when I use ```using```

This 'demo' program only has one worksheet in a workbook being created from scratch, so the code could technically be reduced by simply Adding the worksheet to the workbook instead of testing for its pre-existence in the workbook.  The only reason for the existence test in this demo is to also test the 'test' procedure.  I should just remove the test test to reduce confusion.  Then I can also simply use ```using```

**Comment by vbjay** [comment]
I showed you an example on how to use the using block.

Along with the ?: Operator it will work for the conditional sheet
assignment too.

**Comment by ajstadlin** [comment]
I reworked the code to encapsulate the Workbook and Worksheet objects in ```using``` scopes.

This also removes the conditional assignment for the worksheet.  The test will still "work" but I don't think I can change the worksheet assignment within its ```using { ... }``` scope.  In other words, if used with a existing workbook that might already have a worksheet, I can't select either to create the worksheet or use the existing one - each within their own ```using(new) { ... }``` OR ```using(existing){ ... }``` scopes and then to construct the worksheet outside of its scope.

I might try something like this pseudo code:

```cs
void WorksheetBuilder()
{
  using (XLWorkbook myXlBook = new XLWorkbook())
  {

  IXLWorksheet myXlSheet = null;
  if (WorksheetExists("VENUS"))
  {
    using (myXlSheet = ExistingWorksheet("VENUS"))
    {
      // Call a procedure to construct the worksheet contents.  false = using pre-existing worksheet
      ConstructMyWorksheetContents(ref myXlSheet, false);
      // I better save the workbook here because I don't know if the Workbook will be intact outside of the worksheet using scope.
      myXlBook.SaveAs("Mars.xlsx");     
    } // dispose using existing worksheet
  }
  else
  {
    using (myXlSheet = myXlBook.Worksheets.Add("VENUS"))
    {
      // Call a procedure to construct the worksheet contents.  true = using a new worksheet
      ConstructMyWorksheetContents(ref myXlSheet, true);
      // I better save the workbook here because I don't know if the Workbook will be intact outside of the worksheet using scope.
      myXlBook.SaveAs("Mars.xlsx");     
    } // dispose using new worksheet
  }  

  // Test stuff...
  try
  {
    // Construct the Worksheet
    myXlSheet.Cell(1,1).Value = "MSDN says this will throw an exception";
  }
  catch (Exception x)
  {
    Console.WriteLine("MSDN was right! " + x.Message);
  }

   // Unknown behavior?  Does the workbook still have the worksheet? or was the worksheet disposed?
  myXlBook.SaveAs("Mars.xlsx");

  } // dispose using workbook
}

void ConstructMyWorksheetContents(ref IXLWorksheet xlSheet, bool isNewSheet);
{
  // Construct the worksheet contents here to avoid duplicating code.
}

```

**Comment by ajstadlin** [comment]
Thank you for enlightening me on using ```using```!

The point of this demo project is to send ClosedXML XLSX files to Gmail and troubleshoot why they are not compatible with iPhone.  Refactoring the code to use ```using``` does not change the purpose or results, but it is a nice place for me to try it out.

**Comment by vbjay** [comment]
Of course. Why I pointed you to it.

**Comment by ajstadlin** [comment]
> That's because you are doing it wrong
```
XlWorkbook wb =null;
Try
{
Using (wb= new XlWorkbook())
{  ...  }

- [MSDN:  Using statement (C# Reference)](https://msdn.microsoft.com/en-us/library/yh598w02.aspx).  The following is quoted from that reference.

> **You can instantiate the resource object and then pass the variable to the using statement, but this is not a best practice.** In this case, the object remains in scope after control leaves the using block even though it will probably no longer have access to its unmanaged resources. In other words, it will no longer be fully initialized. If you try to use the object outside the using block, you risk causing an exception to be thrown. For this reason, it is generally better to instantiate the object in the using statement and limit its scope to the using block.

My personal note:  This is clearly not a best practice because the ```using``` syntax does not work consistently when the objects are declared outside of the ```using``` scope.  For example, when the 2 object of the same type are declared outside of the ```using``` scope, combining them into a single as in: 
 ```using( object1 = new Object(), object2 = new Object() )``` does not compile.

However ```using(Object object1 = new Object(), object2 = new Object() )``` is usable syntax.
